### PR TITLE
Print link to test-version zip in PR discussions

### PR DESCRIPTION
**Pull request by merydian**
When opening a new PR a .zip file with the corresponding plugin test-version will be created. A comment containing a link to this .zip will automatically be printed in the respective PR discussion.

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by rcoup** [comment]
I don't know whether this is reusing code from elsewhere, but couldn't we simplify it _a lot_?

- use the existing artifact name (or based on sha) rather than synthesizing a version
- get the artifact id directly from upload-artifact and add the comment based on that
- add a link to the artifact's URL rather than downloading and re-attaching
-

**Comment by nyalldawson** [comment]
@rcoup 

> I don't know whether this is reusing code from elsewhere, but couldn't we simplify it a lot?

I don't think so, no. It's based on the same workflow from the QGIS repo. The tricky bit is that it's not possible for a workflow run from a forked repo to make comments on the pull request on a different repository. That forces the two workflow approach, where one MUST be run from the master branch in the target repository. I spent many hours trying to get the QGIS workflow working and this was the only reliable approach I could find...

**Review by rcoup — APPROVED** [review]
Fair enough! GHA can be pretty frustrating at times

**Comment by nyalldawson** [comment]
@rcoup 
> GHA can be pretty frustrating at times

Totally! Such a frustrating, impossible to debug, black box :scream_cat:

**Pull request merged**
