### PR TITLE
Ensure border doesn't get obscured by thumbnails 

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by BallJonathan** [comment]
@nyalldawson This looks great in 'popular' but is now missing any outline or highlighting in the 'browse' search result.

**Comment by nyalldawson** [comment]
@BallJonathan got a screenshot?

**Comment by BallJonathan** [comment]
In the previous version, cards would all have a fine grey line, which when thicker on mouse over. Here is an example:
image

In the build from this PR I see this:
image

**Comment by nyalldawson** [comment]
Odd... let me try an alternative approach!

**Comment by BallJonathan** [comment]
Also noting in the Popular panel, the out line is visible on the top and left of the thumbnail, but not the bottom
image

**Comment by BallJonathan** [comment]
easier to see here 
image

**Comment by nyalldawson** [comment]
@BallJonathan can you test now?

**Comment by BallJonathan** [comment]
That much better, but it is still missing the outline on the bottom of the thumbnails
image

**Comment by nyalldawson** [comment]
@BallJonathan is that ONLY in the popular/recent views?

**Comment by BallJonathan** [comment]
Yes. I dont see the issue in Browse anymore.

**Comment by nyalldawson** [comment]
How about now?

**Comment by BallJonathan** [comment]
Perfect! Done

**Comment by nyalldawson** [comment]
Woohoo! Got there!

**Pull request merged**
