### PR TITLE
Use QWidget.window() rather than QWidget.screen()

### PR DESCRIPTION
**Pull request by pfw**
To support builds of QGIS against QT before 5.14 and deal with #168

### CODE REVIEW

**Comment by nyalldawson** [comment]
This should actually be conditional on the qt version -- .window has been deprecated and isn't available in newer qt versions

**Comment by nyalldawson** [comment]
> My inclination would to do a hasattr or similar on the QWidget instance to do that rather than explicitly checking a version - can you see any problem with that?

I lean toward explicit version checking. While hasattr is more "pythonic", if we explicitly version check then it gives a definite indication of when its safe to drop the compatibility code.

**Comment by pfw** [comment]
Works for me.

**Comment by pfw** [comment]
I'm struggling to find the deprecation for QWidget.window or QWindow.screen and not having any luck... https://doc.qt.io/qt-6/qwidget-obsolete.html and there isn't a QWindow deprecation list - is this hidden away somewhere?

**Comment by nyalldawson** [comment]
Argh sorry, I'm getting my memory confused. It was the QApplication level window/screen methods which were removed. We are good to change whole to window().screen()

**Comment by pfw** [comment]
Good one ;-) I was getting my head melted by the organisation of the QT docs so wouldn't have been surprised if I had missed something.

**Pull request merged**
