### PR TITLE
Switch to narrow cards when list width shrinks too small to avoid thumbnail hiding

### LINKED ISSUE #285: Thumbnails disappear at narrow widths
At narrower plugin widths, the data card thumbnails disappear. 

Please ensure thumbnails are always present on the card, regardless of plugin width. 

If data card compression (title, etc) is a problem, we can request some design help.

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #285

### CODE REVIEW

**Comment by nyalldawson** [comment]
@BallJonathan can you give this a test run? I think it's an elegant solution, but more testing would be good

**Comment by BallJonathan** [comment]
Nah. I'm not sure that works quite right either. Is it possible to have a min panel width for the plugin? I'll talk with Tim and see what to do.

**Comment by BallJonathan** [comment]
I'm waiting for some of Tim's time, but here is an example of how the web platform deals with the narrowest panel we allow. I assume he will ask us to replicate this.  
image

**Comment by BallJonathan** [comment]
Tim will get us designs in a day or two. Hold fire until then.

**Comment by BallJonathan** [comment]
@nyalldawson You should receive a Figma invite any moment. Please try to replicate the design. Let me know if there are any issues.

**Comment by BallJonathan** [comment]
@nyalldawson Are you able to access the figma?

**Comment by nyalldawson** [comment]
@BallJonathan I haven't received a link yet -- can you re-send?

**Comment by BallJonathan** [comment]
Sent via email

**Comment by nyalldawson** [comment]
@BallJonathan ok, ready for testing now!

**Comment by BallJonathan** [comment]
@nyalldawson A couple of changes:

1. Switch to the narrower design laters. Allow the date to get much closer to the get button before switching.
2. Change the design. Keep the Title font size the same at all card sizes.
3. There is a pixel or 2 gap on the top and bottom of the thumbnails at some widths 
4. At the narrowest plugin width, cards should not push out to the right. Currently, the scroll bar and cards are popping out.

**Comment by nyalldawson** [comment]
@BallJonathan should all be addressed now!

**Comment by BallJonathan** [comment]
Thanks Nyall, I'll have a look later today.

**Comment by BallJonathan** [comment]
I'm happy with this. Thanks.

**Pull request merged**
