### PR TITLE
Attempt to avoid "flashing" results widget

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by BallJonathan** [comment]
@nyalldawson  
1. That fixes the initial flashing, but it now flashes on login. 
https://github.com/koordinates/koordinates-qgis-plugin/assets/113562913/e4877013-bd52-4fc3-afd7-614d21214893

2. No filter descriptor in "groups filter". I'm sure it was there before. 
image

**Comment by nyalldawson** [comment]
@BallJonathan this is still a Wip 😉

**Comment by BallJonathan** [comment]
Opps. I got an email notification and jumped straight into testing. lol.

**Comment by BallJonathan** [comment]
@nyalldawson ready to test?

**Comment by nyalldawson** [comment]
Not yet, still working on it

**Comment by nyalldawson** [comment]
@BallJonathan ok, ready to test!

**Pull request merged**
